import { Registry } from '../../registries/Registry'
import type { MemoryDefinition } from './memoryTypes'

// Phase 16 §16.1 — Memory registry.
//
// A registry holds the canonical definitions for memory ids the sim
// uses. Modules call `ctx.addMemory({ id, ... })` and the memory module
// looks up the registry to fill in defaults (type, duration, strength,
// stacking strategy, tags). Memories with no registered definition are
// still allowed — they default to a `timed` memory with no duration.

export const memoryRegistry = new Registry<MemoryDefinition>()

// Phase 16 §16.3 — required default definitions cover the obvious
// memory-creation points wired through Phases 12–15. The numbers below
// follow the spec recommendations: timed memories last 7–21 days,
// strength sits around 30–50, and stacking favours `increase_strength`
// for repeated-event memories (watered ale, missed wages) so they
// compound without exploding into duplicates.
export const REQUIRED_MEMORY_DEFINITIONS: MemoryDefinition[] = [
  // --- Owner-action memories ---
  {
    id: 'watered_ale_recently',
    type: 'timed',
    label: 'Watered Down Ale',
    defaultDurationDays: 14,
    defaultStrength: 40,
    tags: ['stock', 'ale', 'deception', 'customer_trust'],
    relatedSystems: ['stock', 'reputation'],
    stacking: 'increase_strength',
  },
  {
    id: 'staff_bonus_paid_recently',
    type: 'timed',
    label: 'Staff Bonus Paid',
    defaultDurationDays: 10,
    defaultStrength: 35,
    tags: ['staff', 'wages', 'morale'],
    relatedSystems: ['staff'],
    stacking: 'refresh',
  },
  {
    id: 'roof_patched_recently',
    type: 'timed',
    label: 'Roof Patched',
    defaultDurationDays: 14,
    defaultStrength: 30,
    tags: ['repair', 'roof', 'maintenance'],
    relatedSystems: ['areas'],
    stacking: 'refresh',
  },
  {
    id: 'cellar_fumigated_recently',
    type: 'timed',
    label: 'Cellar Fumigated',
    defaultDurationDays: 10,
    defaultStrength: 35,
    tags: ['cellar', 'pests', 'sanitation'],
    relatedSystems: ['areas'],
    stacking: 'refresh',
  },
  {
    id: 'area_cleaned_recently',
    type: 'timed',
    label: 'Area Cleaned',
    defaultDurationDays: 5,
    defaultStrength: 25,
    tags: ['cleanliness', 'maintenance'],
    relatedSystems: ['areas'],
    stacking: 'refresh',
  },
  {
    id: 'area_repaired_recently',
    type: 'timed',
    label: 'Area Repaired',
    defaultDurationDays: 14,
    defaultStrength: 30,
    tags: ['repair', 'maintenance'],
    relatedSystems: ['areas'],
    stacking: 'refresh',
  },

  // --- Weekly memories ---
  {
    id: 'wages_paid_recently',
    type: 'timed',
    label: 'Wages Paid',
    defaultDurationDays: 7,
    defaultStrength: 35,
    tags: ['staff', 'wages'],
    relatedSystems: ['staff'],
    stacking: 'refresh',
  },
  {
    id: 'wages_unpaid_recently',
    type: 'timed',
    label: 'Wages Unpaid',
    defaultDurationDays: 14,
    defaultStrength: 50,
    tags: ['staff', 'wages', 'risk'],
    relatedSystems: ['staff'],
    stacking: 'increase_strength',
  },

  // --- Monthly memories ---
  {
    id: 'rent_paid_recently',
    type: 'timed',
    label: 'Rent Paid',
    defaultDurationDays: 14,
    defaultStrength: 35,
    tags: ['rent', 'landlord'],
    relatedSystems: ['monthly'],
    stacking: 'refresh',
  },
  {
    id: 'rent_missed_recently',
    type: 'timed',
    label: 'Rent Missed',
    defaultDurationDays: 28,
    defaultStrength: 55,
    tags: ['rent', 'landlord', 'risk'],
    relatedSystems: ['monthly'],
    stacking: 'increase_strength',
  },
  {
    id: 'first_rent_paid',
    type: 'fact',
    label: 'First Rent Paid',
    defaultStrength: 60,
    tags: ['rent', 'milestone'],
    relatedSystems: ['monthly'],
    stacking: 'replace',
  },
  {
    id: 'inspection_warning_recently',
    type: 'timed',
    label: 'Inspection Warning',
    defaultDurationDays: 28,
    defaultStrength: 60,
    tags: ['inspection', 'warning', 'risk'],
    relatedSystems: ['monthly', 'inspection'],
    stacking: 'increase_strength',
  },

  // --- Service memories ---
  {
    id: 'recent_brawl',
    type: 'timed',
    label: 'Recent Brawl',
    defaultDurationDays: 7,
    defaultStrength: 40,
    tags: ['violence', 'incident'],
    relatedSystems: ['service'],
    stacking: 'increase_strength',
  },
  {
    id: 'ale_shortage_recently',
    type: 'timed',
    label: 'Ale Shortage',
    defaultDurationDays: 5,
    defaultStrength: 35,
    tags: ['stock', 'ale', 'shortage'],
    relatedSystems: ['stock', 'service'],
    stacking: 'increase_strength',
  },
  {
    id: 'stew_shortage_recently',
    type: 'timed',
    label: 'Stew Shortage',
    defaultDurationDays: 5,
    defaultStrength: 30,
    tags: ['stock', 'stew', 'shortage'],
    relatedSystems: ['stock', 'service'],
    stacking: 'increase_strength',
  },
  {
    id: 'merchants_unhappy_recently',
    type: 'timed',
    label: 'Merchants Unhappy',
    defaultDurationDays: 7,
    defaultStrength: 35,
    tags: ['customers', 'merchants', 'complaint'],
    relatedSystems: ['customers'],
    stacking: 'increase_strength',
  },

  // Phase 33 §33.5 / §33.7 — owner project + social-action memories.
  // These power the weekly community routine planned for Phase 34: a
  // recently-comforted staff member or a recently-apologized-to regular
  // should weigh on later scene generation and rumour propagation.
  {
    id: 'project_completed_recently',
    type: 'timed',
    label: 'Project Completed',
    defaultDurationDays: 21,
    defaultStrength: 50,
    tags: ['owner_action', 'project', 'milestone'],
    relatedSystems: ['ownerActions', 'projects'],
    stacking: 'refresh',
  },
  {
    id: 'staff_comforted_recently',
    type: 'timed',
    label: 'Staff Comforted',
    defaultDurationDays: 7,
    defaultStrength: 35,
    tags: ['owner_action', 'social', 'staff', 'morale'],
    relatedSystems: ['ownerActions', 'staff'],
    stacking: 'refresh',
  },
  {
    id: 'regular_apologized_to_recently',
    type: 'timed',
    label: 'Regular Apologized To',
    defaultDurationDays: 10,
    defaultStrength: 40,
    tags: ['owner_action', 'social', 'regulars'],
    relatedSystems: ['ownerActions', 'regulars'],
    stacking: 'refresh',
  },

  // Phase 32 §32.5 — scene-driven memories. The service scene builder
  // emits these only when the scene should influence future days; the
  // scene itself stays a structural record on the daily result so the
  // history/cause trail does not double-record.
  {
    id: 'regular_complained_recently',
    type: 'timed',
    label: 'Regular Complained',
    defaultDurationDays: 7,
    defaultStrength: 35,
    tags: ['service', 'scene', 'regulars', 'complaint'],
    relatedSystems: ['service', 'regulars'],
    stacking: 'increase_strength',
  },
  {
    id: 'staff_snapped_recently',
    type: 'timed',
    label: 'Staff Snapped',
    defaultDurationDays: 7,
    defaultStrength: 40,
    tags: ['service', 'scene', 'staff', 'stress'],
    relatedSystems: ['service', 'staff'],
    stacking: 'increase_strength',
  },
  {
    id: 'area_problem_publicly_noticed',
    type: 'timed',
    label: 'Area Problem Publicly Noticed',
    defaultDurationDays: 7,
    defaultStrength: 30,
    tags: ['service', 'scene', 'areas'],
    relatedSystems: ['service', 'areas'],
    stacking: 'increase_strength',
  },

  // --- Pattern memories ---
  {
    id: 'repeated_ale_shortages',
    type: 'pattern',
    label: 'Repeated Ale Shortages',
    defaultDurationDays: 21,
    defaultStrength: 60,
    tags: ['pattern', 'stock', 'ale', 'shortage'],
    relatedSystems: ['stock', 'reputation'],
    stacking: 'refresh',
  },
  {
    id: 'repeated_unpaid_wages',
    type: 'pattern',
    label: 'Repeated Unpaid Wages',
    defaultDurationDays: 21,
    defaultStrength: 65,
    tags: ['pattern', 'staff', 'wages', 'risk'],
    relatedSystems: ['staff'],
    stacking: 'refresh',
  },
  {
    id: 'habitual_roof_neglect',
    type: 'pattern',
    label: 'Habitual Roof Neglect',
    defaultDurationDays: 28,
    defaultStrength: 55,
    tags: ['pattern', 'maintenance', 'roof'],
    relatedSystems: ['areas'],
    stacking: 'refresh',
  },
  {
    id: 'merchant_decline_pattern',
    type: 'pattern',
    label: 'Merchant Decline',
    defaultDurationDays: 28,
    defaultStrength: 60,
    tags: ['pattern', 'customers', 'merchants'],
    relatedSystems: ['customers', 'reputation'],
    stacking: 'refresh',
  },

  // Phase 36 §36.3 — Staff entity memories.
  //
  // Staff members keep grudges, gratitudes, and confidence shifts. The
  // memory module stores them under `metadata.owner = { kind: 'staff' }`
  // via `ctx.addEntityMemory`; the registry entry below sets the
  // duration / stacking / tags so the resulting memory carries
  // consistent decay regardless of where in the codebase it gets
  // emitted.
  {
    id: 'staff_publicly_blamed',
    type: 'grudge',
    label: 'Staff Publicly Blamed',
    defaultDurationDays: 42,
    defaultStrength: 45,
    defaultDecayRate: 1,
    tags: ['staff', 'blame', 'morale', 'identity'],
    relatedSystems: ['staff', 'attribution'],
    stacking: 'increase_strength',
  },
  {
    id: 'staff_comforted_after_bad_shift',
    type: 'timed',
    label: 'Staff Comforted After Bad Shift',
    defaultDurationDays: 10,
    defaultStrength: 35,
    tags: ['staff', 'morale', 'identity', 'social'],
    relatedSystems: ['staff'],
    stacking: 'refresh',
  },
  {
    id: 'staff_given_bonus',
    type: 'timed',
    label: 'Staff Given Bonus',
    defaultDurationDays: 14,
    defaultStrength: 45,
    tags: ['staff', 'wages', 'morale', 'identity'],
    relatedSystems: ['staff'],
    stacking: 'refresh',
  },
  {
    id: 'staff_overworked_recently',
    type: 'timed',
    label: 'Staff Overworked Recently',
    defaultDurationDays: 10,
    defaultStrength: 40,
    tags: ['staff', 'stress', 'identity', 'risk'],
    relatedSystems: ['staff'],
    stacking: 'increase_strength',
  },
  {
    id: 'staff_saved_from_angry_customer',
    type: 'timed',
    label: 'Staff Saved From Angry Customer',
    defaultDurationDays: 14,
    defaultStrength: 40,
    tags: ['staff', 'identity', 'gratitude'],
    relatedSystems: ['staff', 'service'],
    stacking: 'refresh',
  },
  {
    id: 'staff_mistake_forgiven',
    type: 'timed',
    label: 'Staff Mistake Forgiven',
    defaultDurationDays: 14,
    defaultStrength: 35,
    tags: ['staff', 'identity', 'gratitude'],
    relatedSystems: ['staff'],
    stacking: 'refresh',
  },
  {
    id: 'staff_mistake_punished',
    type: 'grudge',
    label: 'Staff Mistake Punished',
    defaultDurationDays: 28,
    defaultStrength: 45,
    tags: ['staff', 'identity', 'blame', 'morale'],
    relatedSystems: ['staff'],
    stacking: 'increase_strength',
  },
  {
    id: 'staff_hidden_talent_noticed',
    type: 'fact',
    label: 'Staff Hidden Talent Noticed',
    defaultStrength: 50,
    tags: ['staff', 'identity'],
    relatedSystems: ['staff'],
    stacking: 'replace',
  },

  // Phase 36 §36.3 — Regular customer memories.
  {
    id: 'regular_refused_tab',
    type: 'grudge',
    label: 'Regular Refused Tab',
    defaultDurationDays: 21,
    defaultStrength: 40,
    tags: ['regular', 'tab', 'service', 'irritation'],
    relatedSystems: ['regulars', 'service'],
    stacking: 'increase_strength',
  },
  {
    id: 'regular_given_free_meal',
    type: 'timed',
    label: 'Regular Given Free Meal',
    defaultDurationDays: 14,
    defaultStrength: 40,
    tags: ['regular', 'gratitude', 'service'],
    relatedSystems: ['regulars'],
    stacking: 'refresh',
  },
  {
    id: 'regular_embarrassed_publicly',
    type: 'grudge',
    label: 'Regular Embarrassed Publicly',
    defaultDurationDays: 28,
    defaultStrength: 50,
    tags: ['regular', 'blame', 'identity'],
    relatedSystems: ['regulars'],
    stacking: 'increase_strength',
  },
  {
    id: 'regular_injured_in_brawl',
    type: 'grudge',
    label: 'Regular Injured In Brawl',
    defaultDurationDays: 42,
    defaultStrength: 55,
    tags: ['regular', 'violence', 'incident'],
    relatedSystems: ['regulars', 'service'],
    stacking: 'increase_strength',
  },
  {
    id: 'regular_helped_by_owner',
    type: 'timed',
    label: 'Regular Helped By Owner',
    defaultDurationDays: 21,
    defaultStrength: 45,
    tags: ['regular', 'gratitude', 'identity'],
    relatedSystems: ['regulars'],
    stacking: 'refresh',
  },
  {
    id: 'regular_favorite_order_remembered',
    type: 'timed',
    label: 'Regular Favorite Order Remembered',
    defaultDurationDays: 14,
    defaultStrength: 35,
    tags: ['regular', 'gratitude', 'service'],
    relatedSystems: ['regulars'],
    stacking: 'refresh',
  },
  {
    id: 'regular_complaint_ignored',
    type: 'grudge',
    label: 'Regular Complaint Ignored',
    defaultDurationDays: 21,
    defaultStrength: 40,
    tags: ['regular', 'complaint', 'blame', 'irritation'],
    relatedSystems: ['regulars'],
    stacking: 'increase_strength',
  },

  // Phase 36 §36.3 — Supplier memories.
  {
    id: 'supplier_paid_late',
    type: 'grudge',
    label: 'Supplier Paid Late',
    defaultDurationDays: 28,
    defaultStrength: 45,
    tags: ['supplier', 'payment', 'relationship'],
    relatedSystems: ['suppliers'],
    stacking: 'increase_strength',
  },
  {
    id: 'supplier_blamed_for_bad_stock',
    type: 'grudge',
    label: 'Supplier Blamed For Bad Stock',
    defaultDurationDays: 28,
    defaultStrength: 50,
    tags: ['supplier', 'blame', 'stock'],
    relatedSystems: ['suppliers', 'stock'],
    stacking: 'increase_strength',
  },
  {
    id: 'supplier_given_fair_deal',
    type: 'timed',
    label: 'Supplier Given Fair Deal',
    defaultDurationDays: 21,
    defaultStrength: 40,
    tags: ['supplier', 'gratitude', 'relationship'],
    relatedSystems: ['suppliers'],
    stacking: 'refresh',
  },
  {
    id: 'supplier_cheated_by_owner',
    type: 'grudge',
    label: 'Supplier Cheated By Owner',
    defaultDurationDays: 42,
    defaultStrength: 60,
    tags: ['supplier', 'blame', 'risk'],
    relatedSystems: ['suppliers'],
    stacking: 'increase_strength',
  },
  {
    id: 'supplier_helped_during_shortage',
    type: 'timed',
    label: 'Supplier Helped During Shortage',
    defaultDurationDays: 21,
    defaultStrength: 45,
    tags: ['supplier', 'gratitude', 'crisis'],
    relatedSystems: ['suppliers', 'stock'],
    stacking: 'refresh',
  },
  {
    id: 'supplier_exclusive_offer_refused',
    type: 'grudge',
    label: 'Supplier Exclusive Offer Refused',
    defaultDurationDays: 21,
    defaultStrength: 35,
    tags: ['supplier', 'relationship'],
    relatedSystems: ['suppliers'],
    stacking: 'refresh',
  },

  // Phase 36 §36.3 — Faction memories.
  {
    id: 'faction_discount_honoured',
    type: 'timed',
    label: 'Faction Discount Honoured',
    defaultDurationDays: 21,
    defaultStrength: 40,
    tags: ['faction', 'gratitude', 'policy'],
    relatedSystems: ['factions'],
    stacking: 'refresh',
  },
  {
    id: 'faction_discount_revoked',
    type: 'grudge',
    label: 'Faction Discount Revoked',
    defaultDurationDays: 28,
    defaultStrength: 45,
    tags: ['faction', 'blame', 'policy'],
    relatedSystems: ['factions'],
    stacking: 'increase_strength',
  },
  {
    id: 'faction_member_banned',
    type: 'grudge',
    label: 'Faction Member Banned',
    defaultDurationDays: 42,
    defaultStrength: 55,
    tags: ['faction', 'blame', 'incident'],
    relatedSystems: ['factions'],
    stacking: 'increase_strength',
  },
  {
    id: 'faction_event_hosted',
    type: 'timed',
    label: 'Faction Event Hosted',
    defaultDurationDays: 21,
    defaultStrength: 45,
    tags: ['faction', 'gratitude', 'event'],
    relatedSystems: ['factions'],
    stacking: 'refresh',
  },
  {
    id: 'faction_publicly_insulted',
    type: 'grudge',
    label: 'Faction Publicly Insulted',
    defaultDurationDays: 42,
    defaultStrength: 55,
    tags: ['faction', 'blame', 'social'],
    relatedSystems: ['factions'],
    stacking: 'increase_strength',
  },
  {
    id: 'faction_helped_during_crisis',
    type: 'timed',
    label: 'Faction Helped During Crisis',
    defaultDurationDays: 28,
    defaultStrength: 50,
    tags: ['faction', 'gratitude', 'crisis'],
    relatedSystems: ['factions'],
    stacking: 'refresh',
  },

  // Phase 36 §36.3 — Area memories.
  {
    id: 'area_known_for_brawls',
    type: 'pattern',
    label: 'Area Known For Brawls',
    defaultDurationDays: 28,
    defaultStrength: 55,
    tags: ['area', 'pattern', 'violence', 'atmosphere'],
    relatedSystems: ['areas', 'service'],
    stacking: 'refresh',
  },
  {
    id: 'area_known_for_music',
    type: 'pattern',
    label: 'Area Known For Music',
    defaultDurationDays: 28,
    defaultStrength: 50,
    tags: ['area', 'pattern', 'atmosphere'],
    relatedSystems: ['areas'],
    stacking: 'refresh',
  },
  {
    id: 'area_known_for_bad_smell',
    type: 'pattern',
    label: 'Area Known For Bad Smell',
    defaultDurationDays: 21,
    defaultStrength: 45,
    tags: ['area', 'pattern', 'atmosphere', 'risk'],
    relatedSystems: ['areas'],
    stacking: 'refresh',
  },
  {
    id: 'area_recently_upgraded',
    type: 'timed',
    label: 'Area Recently Upgraded',
    defaultDurationDays: 21,
    defaultStrength: 45,
    tags: ['area', 'project', 'maintenance'],
    relatedSystems: ['areas', 'ownerActions'],
    stacking: 'refresh',
  },
  {
    id: 'area_neglected_too_long',
    type: 'pattern',
    label: 'Area Neglected Too Long',
    defaultDurationDays: 28,
    defaultStrength: 50,
    tags: ['area', 'pattern', 'maintenance', 'risk'],
    relatedSystems: ['areas'],
    stacking: 'refresh',
  },

  // Phase 36 §36.3 — Arc memories. Owner is typically the arc local
  // event id (kind: 'local_event'); subjects/blamed/credited references
  // capture which faction or rival benefited.
  {
    id: 'arc_warning_ignored',
    type: 'grudge',
    label: 'Arc Warning Ignored',
    defaultDurationDays: 42,
    defaultStrength: 50,
    tags: ['arc', 'blame', 'risk'],
    relatedSystems: ['localArcs'],
    stacking: 'increase_strength',
  },
  {
    id: 'arc_preparation_successful',
    type: 'fact',
    label: 'Arc Preparation Successful',
    defaultStrength: 55,
    tags: ['arc', 'milestone', 'gratitude'],
    relatedSystems: ['localArcs'],
    stacking: 'replace',
  },
  {
    id: 'arc_preparation_failed',
    type: 'grudge',
    label: 'Arc Preparation Failed',
    defaultDurationDays: 42,
    defaultStrength: 55,
    tags: ['arc', 'blame', 'risk'],
    relatedSystems: ['localArcs'],
    stacking: 'increase_strength',
  },
  {
    id: 'arc_supplier_side_taken',
    type: 'fact',
    label: 'Arc Supplier Side Taken',
    defaultStrength: 50,
    tags: ['arc', 'supplier', 'identity'],
    relatedSystems: ['localArcs', 'suppliers'],
    stacking: 'replace',
  },
  {
    id: 'arc_rival_advantage_allowed',
    type: 'grudge',
    label: 'Arc Rival Advantage Allowed',
    defaultDurationDays: 42,
    defaultStrength: 50,
    tags: ['arc', 'blame', 'rival'],
    relatedSystems: ['localArcs'],
    stacking: 'increase_strength',
  },

  // Phase 36 §36.6 — Entity-scoped pattern memories. The pattern
  // detector emits these when repeated entity events show up in the
  // memory log; later phases (pressures, issue seeds) will key off the
  // tagged systems.
  {
    id: 'staff_feels_scapegoated',
    type: 'pattern',
    label: 'Staff Feels Scapegoated',
    defaultDurationDays: 28,
    defaultStrength: 60,
    tags: ['pattern', 'staff', 'blame', 'morale', 'identity'],
    relatedSystems: ['staff', 'attribution'],
    stacking: 'refresh',
  },
  {
    id: 'regular_feels_ignored',
    type: 'pattern',
    label: 'Regular Feels Ignored',
    defaultDurationDays: 28,
    defaultStrength: 55,
    tags: ['pattern', 'regular', 'complaint', 'irritation'],
    relatedSystems: ['regulars'],
    stacking: 'refresh',
  },
  {
    id: 'supplier_distrust_pattern',
    type: 'pattern',
    label: 'Supplier Distrust Pattern',
    defaultDurationDays: 28,
    defaultStrength: 60,
    tags: ['pattern', 'supplier', 'distrust', 'risk'],
    relatedSystems: ['suppliers'],
    stacking: 'refresh',
  },
  {
    id: 'area_bad_reputation',
    type: 'pattern',
    label: 'Area Bad Reputation',
    defaultDurationDays: 28,
    defaultStrength: 55,
    tags: ['pattern', 'area', 'atmosphere', 'risk'],
    relatedSystems: ['areas'],
    stacking: 'refresh',
  },

  // --- Future hook examples ---
  {
    id: 'food_poisoning_rumor_possible',
    type: 'future_hook',
    label: 'Food Poisoning Rumor Possible',
    defaultDurationDays: 7,
    defaultStrength: 35,
    tags: ['food_safety', 'rumor', 'customer_trust'],
    relatedSystems: ['stock', 'customers', 'inspection'],
    stacking: 'replace',
  },
  {
    id: 'inspector_followup_possible',
    type: 'future_hook',
    label: 'Inspector Follow-up Possible',
    defaultDurationDays: 14,
    defaultStrength: 45,
    tags: ['inspection', 'risk'],
    relatedSystems: ['inspection'],
    stacking: 'replace',
  },
  {
    id: 'supplier_retaliation_possible',
    type: 'future_hook',
    label: 'Supplier Retaliation Possible',
    defaultDurationDays: 14,
    defaultStrength: 30,
    tags: ['supplier', 'risk'],
    relatedSystems: ['stock'],
    stacking: 'replace',
  },
  {
    id: 'staff_quit_risk_possible',
    type: 'future_hook',
    label: 'Staff Quit Risk',
    defaultDurationDays: 14,
    defaultStrength: 40,
    tags: ['staff', 'risk'],
    relatedSystems: ['staff'],
    stacking: 'replace',
  },
  // Phase 50 / ISSUE-010 — Producers for the three dead-read tags that
  // `culturalTension` aggregates in its `taboo_memory` cause. Each
  // definition includes its mechanical tag (`seating_conflict`,
  // `food_taboo`, `cultural_misunderstanding`) so the
  // `totalMemoryStrengthByTags` call inside the calculator sees them.
  {
    id: 'seating_conflict_recently',
    type: 'timed',
    label: 'Seating Conflict',
    defaultDurationDays: 7,
    defaultStrength: 30,
    tags: ['culture', 'seating_conflict'],
    relatedSystems: ['cultures', 'customers'],
    stacking: 'increase_strength',
  },
  {
    id: 'food_taboo_recently',
    type: 'timed',
    label: 'Food Taboo Encountered',
    defaultDurationDays: 7,
    defaultStrength: 25,
    tags: ['culture', 'food_taboo'],
    relatedSystems: ['cultures', 'stock'],
    stacking: 'increase_strength',
  },
  {
    id: 'cultural_misunderstanding_recently',
    type: 'timed',
    label: 'Cultural Misunderstanding',
    defaultDurationDays: 10,
    defaultStrength: 25,
    tags: ['culture', 'cultural_misunderstanding'],
    relatedSystems: ['cultures'],
    stacking: 'increase_strength',
  },
]

let initialized = false

export function ensureRequiredMemoriesRegistered(): void {
  if (initialized) return
  for (const def of REQUIRED_MEMORY_DEFINITIONS) {
    if (!memoryRegistry.has(def.id)) {
      memoryRegistry.register(def)
    }
  }
  initialized = true
}

ensureRequiredMemoriesRegistered()
