// Phase 125 / ISSUE-094 — Living Cast arc, Phase E.
//
// Render a `Snippet[]` for one slot into the exact `.ts` file shape the
// existing Phase-C pools (`src/cards/compose/pools/<template>/<slot>.ts`)
// use. Pure: same input → byte-identical output. Snippets are sorted by
// (specificity asc, id asc) so the emitter is deterministic regardless
// of the order the model returned them in.

import type { Snippet, SnippetCondition } from '../../src/cards/compose/types'

function specificityOf(s: Snippet): number {
  return s.specificity ?? s.conditions.length
}

function sortSnippetsForEmit(snippets: readonly Snippet[]): Snippet[] {
  return [...snippets].sort((a, b) => {
    const sa = specificityOf(a)
    const sb = specificityOf(b)
    if (sa !== sb) return sa - sb
    return a.id.localeCompare(b.id)
  })
}

function camelCase(id: string): string {
  // Lower camelCase: 'order_line' -> 'orderLine'. Used to derive the
  // exported pool constant name from the slot id, matching the
  // existing pool file convention.
  return id.replace(/_([a-z])/g, (_m, c: string) => c.toUpperCase())
}

function renderConditionValue(v: unknown): string {
  if (typeof v === 'string') return JSON.stringify(v)
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return String(v)
  if (Array.isArray(v)) {
    const parts = v.map((x) => renderConditionValue(x))
    return `[${parts.join(', ')}]`
  }
  // Should be unreachable for valid conditions.
  return JSON.stringify(v)
}

function renderCondition(c: SnippetCondition): string {
  const entries = Object.entries(c).map(
    ([k, v]) => `${k}: ${renderConditionValue(v)}`,
  )
  return `{ ${entries.join(', ')} }`
}

function renderConditionsBlock(conditions: readonly SnippetCondition[]): string {
  if (conditions.length === 0) {
    return '    conditions: [],'
  }
  if (conditions.length === 1) {
    return `    conditions: [\n      ${renderCondition(conditions[0]!)},\n    ],`
  }
  const lines = conditions.map((c) => `      ${renderCondition(c)},`)
  return `    conditions: [\n${lines.join('\n')}\n    ],`
}

function renderSnippet(s: Snippet): string {
  const lines: string[] = []
  lines.push('  {')
  lines.push(`    id: ${JSON.stringify(s.id)},`)
  lines.push(`    text: ${JSON.stringify(s.text)},`)
  lines.push(renderConditionsBlock(s.conditions))
  if (s.specificity !== undefined) {
    lines.push(`    specificity: ${s.specificity},`)
  }
  lines.push('  },')
  return lines.join('\n')
}

export type EmitPoolOptions = {
  templateId: string
  slotId: string
  /** Free-form header note threaded into the file's block comment. */
  header?: string
}

export function emitPoolFile(
  snippets: readonly Snippet[],
  opts: EmitPoolOptions,
): string {
  const sorted = sortSnippetsForEmit(snippets)
  const constName = `${camelCase(opts.slotId)}Pool`
  const header = (
    opts.header ?? `Generated pool for the ${opts.slotId} slot of ${opts.templateId}.`
  )
    .split('\n')
    .map((l) => `// ${l}`)
    .join('\n')
  const lines: string[] = []
  lines.push('// Phase 125 / ISSUE-094 — Living Cast arc, Phase E.')
  lines.push('//')
  lines.push(
    "// Generated by `npm run generate-pool` from a spec under `specs/cards/`.",
  )
  lines.push(
    '// Hand-edit only as a stop-gap; the source of truth is the spec.',
  )
  lines.push('//')
  lines.push(header)
  lines.push('')
  lines.push("import type { SnippetPool } from '../../types'")
  lines.push('')
  lines.push(`export const ${constName}: SnippetPool = {`)
  lines.push(`  slotId: ${JSON.stringify(opts.slotId)},`)
  lines.push('  snippets: [')
  for (const snippet of sorted) {
    lines.push(renderSnippet(snippet))
  }
  lines.push('  ],')
  lines.push('}')
  return lines.join('\n') + '\n'
}
