export { rivalModule, RIVAL_MODULE_ID } from './rivalModule'
export { buildRivalReport, SCOUT_FRESHNESS_DAYS } from './rivalReport'
export {
  BASELINE_CAPABILITY,
  COURTING_FLOOR,
  MAX_RIVAL_MOVE_HISTORY,
  MAX_RIVAL_SETBACKS,
  PRIMARY_RIVAL_ID,
  RECOVERED_SETBACK_RETENTION_DAYS,
  RIVAL_GOALS,
  RivalModuleStateSchema,
  activeCourting,
  bumpRivalTotal,
  courtingFor,
  createInitialRivalModuleState,
  createInitialRivalTotals,
  createRivalActor,
  createRivalRecord,
  getPrimaryRival,
  getRivalModuleState,
  liveSetbacks,
  normalizeRivalSlice,
  openRivalSetback,
  pickRivalName,
  pruneRivalRecords,
  recordRivalMove,
  recordedRivalAppeal,
  recordedRivalPosition,
  rivalCapabilityFromRecordedAppeal,
  rivalLabel,
  rivalRef,
  setbackDrag,
  underTruce,
  writeRival,
  writeRivalSlice,
} from './rivalState'
export {
  competitionSummary,
  competitorChoiceFactorForGroup,
  competitorStandingForGroup,
  competitorStandings,
  houseAppealForGroup,
  positionFitForGroup,
  rivalAppealForGroup,
} from './appeal'
export type { CompetitionSummary, CompetitorStanding } from './appeal'
export {
  COURTING_DECAY_PER_DAY,
  MAX_WORSENED_SEVERITY,
  SETBACK_WEEKLY_WORSENING,
  HOSTILE_RIVAL_ACTIONS,
  RIVAL_ACTOR_ACTION_LIST,
  RIVAL_INTENT_LEAD_DAYS,
  bestPositionFor,
  buildRivalPerception,
  clearRivalIntent,
  deriveRivalGoals,
  ensureRival,
  housesWorstFailing,
  persistRivalActor,
  rivalActionById,
  rivalIntent,
  rumourAgainstRival,
  runRivalActor,
  weeklyBudgetForRival,
  weeklyTakeFor,
  worstServedGroup,
} from './rivalActors'
export {
  RIVAL_DOMINANCE_REVIEW_EVENT,
  RIVAL_PACT_REVIEW_EVENT,
  RIVAL_RETALIATION_EVENT,
  RIVAL_RUMOUR_EXPOSED_EVENT,
  RIVAL_SCHEDULED_EVENTS,
  RIVAL_SCHEDULED_EVENT_TYPES,
  ensureRivalScheduledEventsRegistered,
  scheduleRivalPactReview,
  scheduleRivalRetaliation,
} from './rivalEvents'
export type {
  RivalCapability,
  RivalCourting,
  RivalMarketPosition,
  RivalMenuFocus,
  RivalModuleState,
  RivalMoveEntry,
  RivalRecord,
  RivalSetback,
  RivalSetbackKind,
  RivalTotals,
} from './types'
